### ISSUE TITLE
Chakra UI missing some stuff

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#1]
@JesJehle I tried `chakra-ui` on this one. It seems like it is missing stuff like a `AppBar` or similar. 

Do you know anything more about this? Otherwise I would maybe switch to Material UI or Joy UI, which directly builds on `@mui/core`

**Comment by JesJehle** [comment]
Here is an example for a navbar. It's not a Build in component, but pretty straightforward. 

https://chakra-templates.dev/navigation/navbar

**Comment by JesJehle** [comment]
But there are a number of really nice component libraries on top of chakra ui. 
I will give it a try

https://choc-ui.com/
https://saas-ui.dev/ (free version)

**Comment by mmaelicke** [comment]
I'll close this, as the decision for MUI is already in place
