### ISSUE TITLE
Age of tree only set by the age slider not by the simulation slider

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#103]
The current behavior is highly confusing.
If you add tree 1, change the simulation slider and then add tree 2. Tree 1 is "older" then tree 2. If you now try to change the age individually with the age slider, tree 1 is still "older". 

I would strongly advocate for a solution, where only the age slider (or rather the start and end year) of the individual tree sets the age of the tree, not the simulation slider.
The age slider sets start and end. The simulation slider runs the simulation.
<img width="1123" alt="image" src="https://github.com/hydrocode-de/integra-frontend/assets/23353378/43f74f48-69bf-4dff-81c7-15dea33032bc">

**Comment by mmaelicke** [comment]
that was the intended behavior, the code is complex like hell and the signals mess things up. 
I will fix that in a PR on its own, to track down the problems properly.
