### ISSUE TITLE
Collection of smaller to improvements

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#116]
- [x] using hybrid satellite map for better orientation
- [x] #146
- [x] #165
- [x] move the simulation slider a bit higher to avoid overlap with the footer.
- [ ] ~only display project no saved warning and save button after first editing~
- [ ] ~set fixed age for trees in thumbnails.~
- [x] if tree is hidden because of overlap (mapbox) dragging is not longer possible

**Comment by mmaelicke** [comment]
these are all solved or do not apply anymore
