### ISSUE TITLE
Hinzufügen von Polygone für die Darstellung von Mindestabständen

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#118]
Wir benötigen zwei Arten von Mindestabständen.
* Mindestabstand von Acker zu Baumreihe
* Mindestabstand von Baumreihen.

Vorschlag wäre.
Wir nutzen zwei Polygone mit unterschiedlicher Färbung (Buffer um die Baumlinie), die immer sichtbar sind und das Planen unterstützen.

Verhalten und Funktionalität
* Die Polygone sind immer sichtbar dezent sichtbar und können über einen tooltip erklärt werden.
* Wenn sich die Polygone für den Mindestabstand der Baumreihen überschneiden, gibt es eine Warnung / Pop-up
* Die Polygone für den Mindestabstand zu Ackerflächen kann genutzt werden, um die verbleibende Ackerfläche zu berechnen und den Ertrag evtl zu schätzen / Schatten und Ertragsminderung.

**Comment by mmaelicke** [comment]
This is done and has been changed to the way how distances work now, by comments of @noobla11 and @karpaddel 

Therefore this one is done and I will close it. We might come back to distances, when implementing the Rechtliches
