### ISSUE TITLE
What about Standorteigenschaften?

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#122]
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/47488a94-c729-41d1-a3a5-4a78512c8a3e)
Ich könnte eine API deployen, die die Daten über die google earth engine abfragt. Sollte alles kostenlos sein, braucht aber doch etwas Zeit.
Boden und Nährstoffe sind evtl. nicht so genau (https://developers.google.com/earth-engine/datasets/tags/openlandmap)
Niederschlag und Temperatur sollte kein Problem sein und evtl. spätforest sollte kein Problem sein.
Die Frage ist, was braucht es wirklich? 
Wenn wir den Nutzer alles selbst ausfüllen lassen, ist das auch komisch, denke ich.

**Comment by mmaelicke** [comment]
Ich hab auch code um soil-tiles (oder so ähnlich, hab den Namen gerade vergessen), openweathermap oder den dwd abzufragen. DWD wäre amtlich und höher aufgelöst.

Sehe ich gerade keine große Priorität drin, daher habe ich das selber noch nicht gemacht.

Ich könnte mir vorstellen, dass das alles zu ungenau für den Landwirt ist, der ja den Standort deutlich besser kennt. Kein remote-sensing Produkt kann letztlich mikroklimatische Begebenheiten abbilden, die ja gerade für die Landwirtschaft wichtig sind. Wenn ich z.b. an den Kaiserstuhl denke, da können innerhalb der räumlichen Auflösung große Variationen, je nachdem ob ich an der Ost oder Westseite meinen Acker habe auftreten. Da das ganze ja zum jetzigen Stand nur für den Report ist, würde ich da mal noch keine Zeit drauf verschwenden. Da gibt es größere Baustellen

**Comment by noobla11** [comment]
Wir würden auch sagen, dass es erstmal keine Priorität hat. 
Am Besten wäre es natürlich, wenn der Nutzer die Informationen nicht selber eintragen muss, zumindest nicht zwangsläufig. Cool wäre, wenn es per Default ausgefüllt werden würde und der Nutzer trotzdem die Möglichkeit hat diese Settings zu verändern, falls er genauere Informationen angeben kann/möchte.

**Comment by noobla11** [comment]
> ![image](https://private-user-images.githubusercontent.com/23353378/329212816-47488a94-c729-41d1-a3a5-4a78512c8a3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODQ5NzIsIm5iZiI6MTcxNTU4NDY3MiwicGF0aCI6Ii8yMzM1MzM3OC8zMjkyMTI4MTYtNDc0ODhhOTQtYzcyOS00MWQxLWEzYTUtNGE3ODUxMmM4YTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA3MTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMGI4ZDlmZDRiMThkNzVlNmFhYzNiODBkYTIyMTI1YjVhNzY1ZmUyYzJlNTM2MjE5NWQyZGMxZDZiNzY1MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mre3K7cPPpEdjrVvuIJs7qIo5Yj0aCnuta8a7XDh_aU) Ich könnte eine API deployen, die die Daten über die google earth engine abfragt. Sollte alles kostenlos sein, braucht aber doch etwas Zeit. Boden und Nährstoffe sind evtl. nicht so genau (https://developers.google.com/earth-engine/datasets/tags/openlandmap) Niederschlag und Temperatur sollte kein Problem sein und evtl. spätforest sollte kein Problem sein. Die Frage ist, was braucht es wirklich? Wenn wir den Nutzer alles selbst ausfüllen lassen, ist das auch komisch, denke ich.

Wir haben uns die Daten aus der Google Earth Engine angeschaut und würden folgendes abfragen:
- Precipitation (jährliche Summe)
- Temperature (jährliches Mittel)
- pH Wert (als Kategorie - sauer, basisch, neutral)
- soil taxonomy great groups (übersetzt?)

Spätfrost würden wir dementsprechend rausnehmen. Die Bodennährstoffe könnte man als wahlweise auszufüllendes Feld angeben. Wenn keine Information vorhanden ist könnte "keine Angabe" in der Zusammenfassung stehen. 

Falls die Abfragen die Anwendung zu stark verlangsamen sollten, könnte man die Abfrage auf Temperatur und Niederschlag reduzieren.
