### ISSUE TITLE
How to handle distances?

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#123]
Der Abstand zwischen den Bäumen ist sehr wichtig. Derzeit haben wir die Möglichkeit, den Abstand zwischen den Baumlinien visuell darzustellen oder Mindestabstände durch Baumlinienpuffer einzuhalten.
Eine Distanzmessfunktion würde Sonderfälle abfangen. Wir brauchen aber noch eine einfache Möglichkeit, die Abstände zwischen den Bäumen einfach darzustellen.

Ich sehe dafür zwei Möglichkeiten.
* Für den Baum, der gedragged wird, werden die Abstände zu den nächsten X Bäumen visuell und numerisch dargestellt (vielleicht ist das gar nicht möglich).
* Wir verwenden ein Gitternetz, das wir hinterlegen und einstellen können. Eine Art Hilfslinie.

Was meint ihr dazu?

**Comment by mmaelicke** [comment]
Das ist im Grunde mit Rückmeldung von @noobla11 mit PR #145 erledigt. Wenn wir noch ein GIS-like measurement tool brauchen, wäre das eine extra Entwicklung. 
Wenn gewünscht, könnt ihr, @noobla11 oder @karpaddel diesen Kommentar als neues Issue anlegen und priorisieren.
