### ISSUE TITLE
Tree icons are too large

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#127]
The tree icon images are quite large. On the one hand, that slows the application substantially down. More importantly, we will run out of free quota for the database if we extend the supported trees to more than 4-5. The application will downscale the loaded images to 250x250 px anyway...

We also already ran out of monthly data egress, after only 10 days of development usage (without users). That means, with real users we will run out even quicker. Currently, I am not sure if only smaller images will do the trick here.

There are two options here: 

a) we return to local images again, which is rework on the data model again, and will slow down the application startup time. With the current images, by magnitudes. We need to lower the quality until each image is not more than approx. 500kb.

b) we move to a paid subscription, which is at 25$ a month. hydrocode can cover that for some time from the project money, but after that period, wwd will be responsible for payments.

@JesJehle @noobla11 @karpaddel, thoughts?

**Comment by mmaelicke** [comment]
> We also already ran out of monthly data egress, after only 10 days of development usage (without users). That means, with real users we will run out even quicker. Currently, I am not sure if only smaller images will do the trick here.

Turned out, that this was due to an inifite data-fetching loop in the application. The problem is fixed and the egress should not be a problem from next month on anymore.

The other porblems persist.

**Comment by JesJehle** [comment]
we could use some sort of compression optimization like: 
* https://tinypng.com/
* https://compressjpeg.com/

They normally compress the image to 1/8 of the original without any visual artifacts

They all have some free tires - this could be enough.
@noobla11 @karpaddel could you try some of them?

**Comment by mmaelicke** [comment]
The correct order here is: 

1.  decrease the resolution (!). Then we should be fine. 

2. If not, move to jpeg. 
3. If that is still an issue, compress the jpeg.

As of now, we have no scenario in the application in which we would need full-hd images.

**Comment by noobla11** [comment]
I will upload the images in lower resolution soon, maybe we can work from there.

**Comment by JesJehle** [comment]
Since we (I) exceeded the usage limit, our project is restricted, which results in slower loading of the icons, I guess. 
Although we should be fine from now on, the slow loading probably persist until the end of the month. This is a problem.
Should be upgrade for this moth?
@mmaelicke

**Comment by mmaelicke** [comment]
Right now, it seems to be fine. (We almost doubled the allowed egress right now...). The smaller icons will hopefully solve the problem, because over 90% egress is storage egress. If it is too slow for the presentation, we can upgrade, no problem.

**Comment by noobla11** [comment]
I uploaded the images in 250x250 px on bwsync&share. When the app is downscaling it to this resolution anyways I guess it does not make a difference?
I used IrfanView which is a free program with a batch mode for resizing, changing the data format,  renaming etc.. So if we want to rename the files we can still do it if needed.

**Comment by mmaelicke** [comment]
> I uploaded the images in 250x250 px on bwsync&share. When the app is downscaling it to this resolution anyways I guess it does not make a difference? I used IrfanView which is a free program with a batch mode for resizing, changing the data format, renaming etc.. So if we want to rename the files we can still do it if needed.

I just uploaded the new images and realized afterwards, that they don't have a transparent background anymore. Is it easy for you @noobla11 to change that? 
Names are fine for now, I updated the application to the new naming convention.

**Comment by noobla11** [comment]
Sorry for that, I did not realise this either obviously. I uploaded the correct versions now.
