### ISSUE TITLE
implement 'insects' result card

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#133]
* **Insekten**
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/1555c9bb-0f32-496f-bee1-01f9c8bed9df)

_Originally posted by @JesJehle in https://github.com/hydrocode-de/integra-frontend/issues/120#issuecomment-2098230431_

**Comment by noobla11** [comment]
I just uploaded data for this result card on BWsync&share (Insektendaten). I did not join the data with the big table yet, maybe it is easier this way. 
The pollen volume per larva is given in mm³.  The pollen sum of the individual tree or maybe rather with the pollen sum of the whole system(?) needs to be divided by the pollen volume per larva. It is supposed to give an idea of how many individuals of one species can be supported. 

Is it possible to include this before the presentation? A visual effect on the map is not necessary at this point I think, only an overview in the result card. Maybe we can also talk about the visualisation here.

**Comment by noobla11** [comment]
Wir haben noch einmal über die zeitliche Auflösung gesprochen. Wir denken eine jährliche Auflösung pro Baumart ist ausreichend.  Für die Visualisierung der potentiell unterstützten Insektenlarven könnt ihr euch also an der Biomassegrafik orientieren (Insektenart-Auswahl über Drop-Down). Als Informationstext für die Grafik wäre folgendes gut: 

_**Anzahl potentiell unterstützter Larven von generalistischen Insektenarten**
Dieser Wert ist ein theoretischer Wert der Ihnen die Einschätzung bzw. Vergleichbarkeit des Nahrungsangebots für Insektenlarven ermöglichen soll. Für die Berechnung wird angenommen, dass das gesamte Pollenvolumen des geplanten Systems ausschließlich von der ausgewählten Insektenart aufgebraucht wird, unabhängig von der Übereinstimmung des Blüh- bzw. Aktivitätszeitraums._


Wir haben noch eine weitere Idee zur Visualisierung bzw. was hier in diesem Tab noch dargestellt werden könnte. Wir würden gerne darstellen wie sich der Aktivitätszeitraum der über das Drop-Down Menü ausgewählten Insektenart mit dem gesamten Blühzeitraum des Systems überschneidet. Wir haben uns das so vorgestellt: 

![Bild_2024-06-03_113227999](https://github.com/hydrocode-de/integra-frontend/assets/76469988/fcd7876b-c71b-492b-a337-998c199a13b3)


Bezüglich der Anzahl der maximal möglichen Insektenarten haben wir noch eine Änderung, die wir einfacher mündlich besprechen sollten (hat keine Eile).
