### ISSUE TITLE
storing lat, lng, zoom and bearing in state to navigate between Karte and Zusammenfassung seamlessly.

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#146]
Currently, clicking we lose all the position and zoom level of the map when navigating to zusammenfassung. We should provide a seamless switching of karte and zusammenfassung and start at the position we left.

**Comment by mmaelicke** [comment]
The information is already available as a map signal.

**Comment by JesJehle** [comment]
Ich hab gedacht du bist im Urlaub!

**Comment by mmaelicke** [comment]
> Ich hab gedacht du bist im Urlaub!

Bin ich auch, hab aber mein Handy dabei...

**Comment by mmaelicke** [comment]
This seems to work fine in the latest version. Pitch is not working though. I would consider that a minor issue and actually a bug in mapbox.
