### ISSUE TITLE
Update Baumreihen UI

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#147]
The current UI sucks.  #101 would need to be fixed first.
<img width="375" alt="image" src="https://github.com/hydrocode-de/integra-frontend/assets/23353378/2e82b90c-1595-45c6-addc-e13c371897f6">
I would go back to the last implementation:
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/c8337b79-c6c6-4c0e-904c-126f6b5781d7)

Using the cars / rows to select active tree lines on the map.

**Comment by noobla11** [comment]
I am not sure if this is the right place to mentioned it, but at the moment trees can be added to a tree row but can not be deleted. That means, if you make the mistake to drag one tree too many in the tree row/tree line you can not change it. I don't know how difficult this is, maybe we can also push this to after the presentation.

**Comment by mmaelicke** [comment]
Yeah, this one is due to the new tree-oriented data model surprisingly complicated. Right now, I cannot give a good estimation, how long this would take... Maybe fix this after the presentation. or after the high prio stuff before the presentation

**Comment by mmaelicke** [comment]
and also implement a selection of baumreihen to edit them
