### ISSUE TITLE
Small changes (high priority)

### ISSUE THREAD

**Issue by noobla11** [hydrocode-de/integra-frontend#155]
Considering the presentation we think it is important to apply some (hopefully) minor changes to the appearance of the tool. 

**Typos** - an overall check for typos would be necessary; so far we found three, 
two in the map: 
- [x]  Stamm Länge -> Stammlänge; Baureihe -> Baumreihe 

one in the summary: 
- [x] Bodennährstoff versorgung -> Bodennährstoffversorgung

**Word changes** 
when hovering over the trees (map):  

- [x]  Age -> Alter, Height -> Höhe

when creating a new tree line (map):

- [x] Baumline -> Baumreihe

Standort (summary):

- [x]  in "Jährliche Niederschlagssumme": 600mm -> 600 mm

Without heading (summary):

- [x] "Pollenangebot": µm2 = µm²

**Other changes** 
in module "creating new tree line" (map): 

- [x] aktuelle Reihe -> Aktuelle Reihe

in the individual tree module (map): 

- [x] in Planung = In Planung
- [x] wächst = In Wachstum

in module summary: 

- [ ] change headings to bold (e.g. Flächenübersicht), subheadings bold (e.g. Landwirtschaft), text regular size and same size as subheading are now (e.g. Feldfrucht mit Raps und Winterweizen)

in module "Standort" (summary):

- [x] remove (Spät-)frostgefahr

Map and map in summary: 

- [x] map in the summary is still in default zoom and not zoomed to the planned system - if possible it would be nice to show an example here instead (maybe just a picture)
- [x] also every time you switch the tabs between map and summary the zoom is set to the default - it would be good if the zoom is fixed when switching tabs (at least when going back to the map, assuming the map in the summary is a picture)

**Comment by mmaelicke** [comment]
> * [ ]  change headings to bold (e.g. Flächenübersicht), subheadings bold (e.g. Landwirtschaft), text regular size and same size as subheading are now (e.g. Feldfrucht mit Raps und Winterweizen)

This would change the Heading everywhere in the application, which does not look good. If this is an important issue to you, you can open a new issue from this comment, then I implement the Summary with custom heading
