### ISSUE TITLE
adding naturschutz, Natura2000, FFH, Biotope as wms layers (clickable?)

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#165]
I only turned this one into an issue to discuss how relevant this one is. 

We would use this information on the Zusammenfassung, but would also have to host the data ourselves. Or rely on the WMS to actually return point information (not every WMS exposes this feature). But then we still could only test a single point if it is in a protection area. 

From my feeling this one is super-low priority and I would vote for leaving it completely away and close this issue along with #116 (which would finally be solved then)

comments @JesJehle, @noobla11, @karpaddel

**Comment by karpaddel** [comment]
We agree on this one. 

Maybe we can think about another option to integrate the nature conservation topic. For example, as an option where the users can choose between different conservation classes themselves. Maybe in the summary tab?

**Comment by mmaelicke** [comment]
I agree. Then I will close this issue and we come back to protection areas as soon as the summary is fully implemented
