### ISSUE TITLE
State of Data for the Summary page

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#167]
@karpaddel @noobla11 

There is still a lot of work ahead of us, in order to wire up the 'Zusammenfassung' tab with the actual data of the simulation.
As a general question: 

Does the Zusammenfassung summarize the current state of the system, or the state after 100 years?

that should be agreed upon and not changed anymore.
From a technical point of view: The current state is easier to implement, but computationally more demanding for the application.

To me personally, using the current state makes sense, as it is the more flexible solution. At the same time it requires the user to move the slider to 100 (or 80) years, before switching tabs. I can't really decide this, but need to know to proceed. :)

---
In any case, the implementation will take some time as the tab is only a mockup so far. Thus, we should not wait too long with making a decision.

**Comment by karpaddel** [comment]
We would like the option of the current state.

It would be nice though, to have the option to change the current year within the 'Zusammenfassung' tab. Similar to this, where the green year can be changed:

<img width="945" alt="image" src="https://github.com/hydrocode-de/integra-frontend/assets/153747277/3e576d90-f1cb-4a57-8708-57b7359c9243">

**Comment by mmaelicke** [comment]
Ok, I'll look into that. I am not sure, how much the 'simulation' depends on the components of the map being present. If data-model does currently not support this, I try to estimate the refactoring amount necessary.

**Comment by karpaddel** [comment]
Please can you elaborate on this, we don't really understand the last comment

**Comment by mmaelicke** [comment]
I am not sure, if the tab 'Zusammenfassung' can actually **change** the time step without messing everything up, as some of the components necessary might be out of context (loosely speaking, they are not available, if not shown). I am not sure about that and have to look into that. 
The Zusammenfassung was conceptualized as a summary, that is shown *after* the simulation. To make it a dynamic part (aka, changing the tilmestep and reacting to changes), might need refactoring. Could be 5 minutes, could be 5 days of refactoring. I have to use a debugger (or dependency graph) and jump more or less line by line through the relevant code, to see, which parts are involved. Then, I can make a precise estimation of the work needed to build this component as requested.

**Comment by karpaddel** [comment]
Okay:) let us discuss this tomorrow, it might not be the highest priority then
