### ISSUE TITLE
'Blühabdeckung' displaying wrong data

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#172]
Currently, the Blühabdeckung in the insects tab is not correct.

I finally found the error and know how to fix it. Unfortunately, this is not an easy fix, as I have to change the plot. The gantt-chart like bar plot cannot handle NaN values in the row, which will happen all the time. @noobla11 @karpaddel, is this correct, that there should be a hole in the bar, if a month is not covered with blossoms, but the the prior and next months are covered?

Thus, I have to rearrange the data to visualize it using the Heatmap component, but adjusting the color-space to make it look like a gantt chart with holes. I see no other option how to implement this.

I moved this into an extra issue, to that #169 can be merged, after the other change requests are implemented.

**Comment by karpaddel** [comment]
Yes, it is correct that there should be a hole in the bar. The solution with the Heatmap component sounds feasible, we hope it will look similar:)
