### ISSUE TITLE
Tree species selection / Baumartenauswahl

### ISSUE THREAD

**Issue by karpaddel** [hydrocode-de/integra-frontend#177]
- We would like to change the overall title from "Bäume hinzufügen" zu "Planung". And we would like to add a new subtitle "Baumartenauswahl"

- Also, currently it is not intuitive that it is possible to add new tree species by clicking in the light gray area. Here we would like to add a Plus-Symbol to improve this. Like in the following graphic (only with round edges for the cross). We would like only one tree icon (Vogelkirsche) to be shown as default.

![Baumarten_hinzufügen](https://github.com/hydrocode-de/integra-frontend/assets/153747277/b16eb278-30fd-4a94-a3b2-3c7c53eb3bbd)

- The german tree species name of selected species should be shown above the icon when hovering above:

![Baumarten_hinzufügen_hover](https://github.com/hydrocode-de/integra-frontend/assets/153747277/754448d4-1f4c-4fc4-adb2-8ae237e0747a)

**Comment by mmaelicke** [comment]
Yeah, this one is already in the pipeline (the plus), just had no time to actually finalize it.

**Comment by noobla11** [comment]
Update on this one: 

![image](https://github.com/hydrocode-de/integra-frontend/assets/76469988/31f31119-4b5f-4545-b6ea-e1aeb4a64af1)
