### ISSUE TITLE
Abundance - Bienen -- additional graph

### ISSUE THREAD

**Issue by noobla11** [hydrocode-de/integra-frontend#183]
Uploaded the data for the graph we talked about yesterday (Bienendaten/Phaenologie_Bienen.csv). We think this is actually the most useful information for the user and would like to have it as first graph: 

![image](https://github.com/hydrocode-de/integra-frontend/assets/76469988/d77d0d8b-5c92-4abd-bb3d-4226ab6341b5)

For the y-axis maybe it is enough to show steps of 10 instead?!

**Comment by noobla11** [comment]
When you are working on this, maybe you can also 

- [ ]  change the title of the tab (Bienen instead of Insekten)
- [ ]  change title of the graph which is the first atm (Anzahl unterstützter Larven pro Jahr), yaxis = Anzahl Larven/Jahr

**Comment by mmaelicke** [comment]
> * [x]   change title of the graph which is the first atm  to "Anzahl unterstützter Larven pro Jahr", yaxis = "Anzahl Larven/Jahr"

Making the y-axis title longer, would mean to increase the plot height to make the title fit. I suggested two possible solutions in #198. You can open a new issue if you feel like you prefer one of them
