### ISSUE TITLE
Glossar tab

### ISSUE THREAD

**Issue by noobla11** [hydrocode-de/integra-frontend#189]
We thought about an additional tab "Glossar" which contains the definition for e.g. the shade calculation, maybe even where the information was gathered etc.. Location would be somewhere next to the "Zusammenfassung" on the right.

Maybe similar to this, if possible:

![Glossar-Beispiel](https://github.com/hydrocode-de/integra-frontend/assets/76469988/46b379a4-69bc-4c0a-9d4a-9249e2af4e10)

**Comment by noobla11** [comment]
@mmaelicke I think it would be good to just have the tab implemented even without content, just so that the user knows it will be there at some point. Therefore I change priority to high. What do you think?

**Comment by mmaelicke** [comment]
To make you aware: The Glossary tab will be hidden at the startup of the application, as the tab bar only shows up, after a reference area has been selected. 
We either accept that, or make the tab-bar visible all the time, which differs from the current behavior
