### ISSUE TITLE
Legal constraints

### ISSUE THREAD

**Issue by noobla11** [hydrocode-de/integra-frontend#191]
This might be painful, but here the results of the meeting with Marina @mmaelicke @JesJehle @karpaddel : 

First of all it would be nice to include some contraints which are not just warnings or notes so that the user is not able to do something "wrong" in order to receive subsidies. I think we talked about this before but somehow forgot about this to be honest. We were thinking about a multiselect option were the user can choose if he wants to comply with the conditions to receive the "Direktzahlungsförderung" or the "Ökoregelungsförderung" OR both. 

E.g. for the "Direktzahlung" there must be 50-200 trees/ha in order to receive funding OR
there must be a minimum of two treerows which do not exceed 40% of the total area

For the "Ökoregelungsförderung" these rules slightly differ. 

@mmaelicke Would it be possible to somehow implement this? I think we do have the necessary data to calculate e.g. the percentage of the treerows. But can you add contraints to the functionality of the application?
 
Further there needs to be some kind of constraint regarding the distance BETWEEN the treerows. Maybe we can implement an additional buffer in which you can not plant any other rows? 

We also talked about information which should be included into the summary. But I would add this to the summary issue? 

We probably need to plan a meeting regarding this topic together with Marina.

**Comment by mmaelicke** [comment]
Yes. We need a meeting. This is not yet specific enough to make a useful estimation in terms of time and practicability. Before I write long monologues on Github, let's meet. I'll send a mail later.

**Comment by noobla11** [comment]
Tables are uploaded on bwSync&Share in /Rechtliches

**Comment by mmaelicke** [comment]
This is only mockup - the constraints are not yet implemented.

Just from a visual point of view, is this going into the right direction? @noobla11 can you feedback, before I go into detailing?
Thanks!

<img width="437" alt="image" src="https://github.com/hydrocode-de/integra-frontend/assets/2826034/b91c977d-6199-4d6c-87b2-0000e7efef68">

**Comment by noobla11** [comment]
Yes this how I imagined it. @JoshuaBWWD you can also share your opinion if you like. 

I would probably call this card "Förderungsbedingungen" or something like that, because this only tells you if you qualify for subsidies.

**Comment by mmaelicke** [comment]
> Yes this how I imagined it. @JoshuaBWWD you can also share your opinion if you like.
 Yeah, sorry, forgot to mention you as well

> I would probably call this card "Förderungsbedingungen" or something like that, because this only tells you if you qualify for subsidies.

alright, then I start the hard part of actually implementing it ^^

**Comment by JoshuaBWWD** [comment]
Hey, sorry for the late response... but yes, looks all (with "Förderungsbedingungen") good to me! For uniformity reasons I would specify on each of the five points, the target in brackets... or what is meant by the 0 of 2 "Baumreihen"? Is it just because of the provisional draft?!

Thanks Joshua

**Comment by mmaelicke** [comment]
Cool. I think it's a bit clearer now. 

I am just wondering if we can maybe skip the OR conditional for the direktzahlung. Having 2 tree-lines at most of 40% of the area is like really easily fulfilled. Having 50 - 200 trees per hectare is crazy much for this application. Typical southern-german fields seem to have something around 3 ha. that would mean you need to drop at least 150 (!) trees onto the map. 
I can't imagine anyone doing that, that's way too anoying. Thus, we will always have a warning on the screen giving the user the feeling that there is something he is doing wrong, but can never accomplish. 

This constraint might come into play if we would have draw-a-line tools. But that will not happen in this project, I guess.
