### ISSUE TITLE
Adding Baumart Table to the Summary

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#193]
![image](https://github.com/hydrocode-de/integra-frontend/assets/2826034/e0a0161f-ac82-4068-b2b8-642c92cd13ed)

@noobla11 @karpaddel  this needs a priority

Questions:

I would suggest not to add two different numbers into a single column, as we cannot use the built-in sorting functionality anymore. So we either make 4 out of the 2 columns, or I test and play around with an option to toggle the content of the table. Or we use a non-sortable column

**Comment by noobla11** [comment]
Chris would like to keep the sorting function. In the first table we omitted Ästung. Also Blütenanzahl is not important, therefore we would like to have Pollen and Nektar in separate columns: 

![image](https://github.com/hydrocode-de/integra-frontend/assets/76469988/5f808aa7-bcaf-448a-a41d-d9b1a1ff4280)
