### ISSUE TITLE
WHat is the easiest way to add a cookie consent in here

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#21]
We need data protection rules and need to figure out which cookies we use and which are for opt-out.

So far: 

1. local storage - but there is no personal data involved 
2. firebase auth - user_id and session_id is stored in a cookie
3. Firebase Hosting does add stuff 
4. Hotjar will most likely add stuff and this will be for opt-out

@JesJehle I know that there is a website that can scan your deployments for used cookies. That could be helpful. Additionally, we maybe want to use something like cookiebot for managing the cookie things instead of building a component on our own

@JesJehle since you like to come up with new fancy things all the time, I guess this one is for you ^^

**Comment by JesJehle** [comment]
* firebase
* hotjar
* mapbox
