### ISSUE TITLE
After reload of details page, empty spinner is shown

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#28]
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/be784c81-21c3-4fca-a58b-bb99e275b8fa)
after reload:
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/c2122999-5d8d-4c8f-9568-ab453422b95a)

A better behavior would restart the app back to home (desktopPage or MobilePage)

**Comment by mmaelicke** [comment]
I will drop a PR implementing this. 

We have to make sure, that this does not cause any undesired non-responding app as the user tries to do something and is constantly redirected. Maybe we would need a little toast with a warning. But I'll try without first.
