### ISSUE TITLE
Empty treeline editing mode after double click

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#29]
If you start editing with a double click, the state is empty and you cannot continue. 
It's possible to go back and start again.
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/2a72a23e-d1db-4baa-a2f8-a5f72d27229a)

**Comment by mmaelicke** [comment]
Double-click ends the editing of the current feature. This is MapboxDraw behavior and cannot be changed. There is also no easy way to distinguish this edit state from the one where something has actually be created to fix this externally. So I only see the option to inform the user about that.

If we enable to opt-in back into the editing mode, the user can also create more than one line at once...

**Comment by mmaelicke** [comment]
I remove the Milestone here, as there is nothing that has to be done in this issue. If we need to take some kind of action (ie add a text or tooltip), we can change this issue or open a new one
