### ISSUE TITLE
Hotjar and Mouseflow basically useless for us

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#54]
@JesJehle  It seems like both can't capture the content of a `<canvas>`. That effectively means, both tools cannot see the map.

<img width="867" alt="image" src="https://github.com/hydrocode-de/integra-frontend/assets/2826034/a27b7016-ebca-4474-b158-63305b89a775">

That is interesting, because it is not that complicated to render a canvas. Maybe we can build something ourselves in Python...

The idea is that we implement a webworker to collect mouse move events and send them to a backend every 10 seconds, additionally, create a screenshot on every click. That could go into firebase, the image maybe even directly into storage. Then, run a function to create the recording and delete all the data again.

I guess that is too much work for now... Maybe there is an alternative out there that can render canvas...

**Comment by mmaelicke** [comment]
Can confirm the same for mouse flow, just got an answer from the support:

<img width="511" alt="image" src="https://github.com/hydrocode-de/integra-frontend/assets/2826034/c7eed3dd-a3e5-4a67-bf8f-e7dab3a058b3">

**Comment by mmaelicke** [comment]
Just confirmed that it is technically possible to build this:

<img width="375" alt="image" src="https://github.com/hydrocode-de/integra-frontend/assets/2826034/3fcb5eb6-a673-48e0-9605-66023cd8e125">

and the data uri is correctly rendered:

<img width="393" alt="image" src="https://github.com/hydrocode-de/integra-frontend/assets/2826034/7194189f-31f8-42b8-a75e-a00a89e62ad8">


and if rerun it captures the current scene: 

<img width="393" alt="image" src="https://github.com/hydrocode-de/integra-frontend/assets/2826034/c2163b98-cfca-4f22-bce5-1fc66f930c14">

with a webworker, we can run this custom code without slowing the page down. Question is then only: where to store the stuff and do we really need this so badly that we can spent a lot of time on this.

**Comment by JesJehle** [comment]
Hi, this sucks! But at the current state it should not be our main concern, unfortunately. Some live usability tests should do it too. I think we should focuse our attention to capturing meaningfull events and plan out a kind of useflow or funnel defined by different events. This should be simple to implement but a little more work to plan. Still we need to decide about an analytics solution. Since we are not using headmaps we could go for Piwik? @mmaelicke what do you think?

**Comment by mmaelicke** [comment]
Hotjar and mouse flow both implement custom events I think. They are up and running. But I guess implementing pewit as well should be as easy, so why not.

We two should start a company to implement the stuff above and tailor it to scientific use cases. I guess a MVP would be 2 weeks of work... The other solutions are all more or less tailored to e-commerce. events, that have nothing to do with spending money are more than rare...^^
Sorry I am too bored at home. Hate being sick.

**Comment by mmaelicke** [comment]
piwik also has a consent manager which relates to #21

**Comment by JesJehle** [comment]
> piwik also has a consent manager which relates to #21

What do you think is it faster and simpler to use hotjar or should be switch to piwki?
Both are free for our use, and we need a banner any way since we use firebase hosting.

**Comment by mmaelicke** [comment]
> > piwik also has a consent manager which relates to #21
> 
> What do you think is it faster and simpler to use hotjar or should be switch to piwki? Both are free for our use, and we need a banner any way since we use firebase hosting.

I already registered at piwik. I will implement it later, than you can have a look at all three products and how the data we need would be implemented.

**Comment by mmaelicke** [comment]
They are all three active now and you should have received invitations from all three providers to your gmail address

**Comment by JesJehle** [comment]
Wow, but this

> @JesJehle we could also go for https://matomo.org/pricing/
> 
> That used to be piwik in the old days. Has to be hosted on our infrastructure, but we could implement this as a service into all our projects. Not for integra now, (maybe later), but as a general pathway to solve this for all our projects at once.

Pretty extensive features, which is nice, but I don't understand the pricing for on premise — do we need to pay for each feature individually? This would be super expensive - If not, this would be super cheap.

**Comment by mmaelicke** [comment]
Shall I implement both or just one of them?

Cookieless is nice, but is it also DSGVO conform? meaning, are we sure that we do not record a session id or something derived from an IP address, that the user has to agree with? How do they do the actual tracking? How can the user opt-out (or to be more precise, how do we ask for consent)?

Apart from that, we do record IP addresses on the Hosting side and mapbox uses a cookie. So we need to specify that in the privacy agreement anyway.

**Comment by JesJehle** [comment]
I think Cookieless would be key, since most people will opt out if they see a cookie banner by default, and we get no analytics.
As I understand it. If we dont track the user over different pages and if we dont send data to the us, we dont need a cookie banner. 
Please have a look at this:
* https://posthog.com/tutorials/cookieless-tracking
* https://plausible.io/data-policy
We don't get as much analytics as we like, but at least we get some.
What do you think?

**Comment by mmaelicke** [comment]
Ok, the one key question is, do we get the analytics that we need?

The other thing that I do not get from the two pages above (just read through them): Setting the cookie is not the problem, but sending the data. So the question of consent has nothing to do with the cookie. Not using a cookie or other user_id is good, because we would definitely need a consent for that. But can we use the tracking in a meaningful way without any user related info? What are we after? What do we need to learn?
And is really nothing (!, not less, but nothing) send to the server that qualifies as derived personal information? To me, these pages do not answer that question.

**Comment by mmaelicke** [comment]
OK, then plausible and postdoc should be options. 
I think, this way we do not need a cookie banner anymore, we only need to inform about mapbox token and firebase hosting in the privacy agreement, that still has to be created and added.

So which one do you want, both for now and then we decide along the way?

**Comment by JesJehle** [comment]
Yes both for now, then we see if we can get more out of posthog then plausible. If yes, we go for posthog if no plausible
