### ISSUE TITLE
Implement reactive custom symbols

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#55]
Based on #50 and related to #22.
@mmaelicke I think you already have an idea of how to implement this with signals.
The symbols would need to:
* react to age slider
* react to tree species selector
* the images should scale on a fixed predefines sizing scale or just make the images of different size
* select the right images based on the age group.

**Comment by mmaelicke** [comment]
refer to my comment https://github.com/hydrocode-de/integra-frontend/issues/22#issuecomment-1820468554 in #22
