### ISSUE TITLE
Helpful hints for first time users

### ISSUE THREAD

**Issue by lucfr** [hydrocode-de/integra-frontend#57]
First time users could be helped by adding a few hints on how to use the app, e.g.:

- Zoom in to start planning (or start the first view of the map more zoomed in)
- After clicking '+ NEU' add a hint to start clicking trees onto the map (not obvious if mouse stays on the sidebar)
- Add a hint to use double click to end a Baumreihe

**Comment by mmaelicke** [comment]
Yeah thanks. We are planning on have a dedicated more to ie. disable the project management on first visit and only display it as needed and stuff.

Your hint are useful and will all be addressed after milestone 1

@JesJehle we can use this issue to collect all the ideas we discussed so far, which are all heading into the same direction as Lucas comments.
