### ISSUE TITLE
Develop a model for projects

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#61]
This relates to #31 

Right now a 'Project' is only a simple string, that identifies a `TreeLine[ ]`. The project itself does not hold any more information. This is becoming a problem, because there actually is a state, that cannot be reflected by a tree-line simply being present.

#### example
The user creates a line and simulates it for 10 Years. Then, a second line is created and another 10 years are simulated. 
In the current instance, the user can slide the simulation back and forth and everything works as expected. 
Next, the tree-lines are persisted into a project, and the browser is re-loaded.  If the project is loaded to the canvas, the **second line is instantly created**, because the editSettings are persisted along with a project. If ones slides the simulation to 100, the first line is 120 years and the second line 110 year old. After one second that state is persisted and if the page is reloaded, there is no option in the simulation to go back, because the silder is at 0 years, but the trees are older than 100 years. Aka. it looks like the app is not responding, although it is working perfectly.

Long story short: a project needs to persist the current state of the simulation along with it to fix the bug. The other option is, that treeAges are reset to 1 on saving. But that would mean, that it is impossible to exactly reproduce a project.

#### solution

I would like to extend the project model as defined here:

https://github.com/hydrocode-de/integra-frontend/blob/07e25c453955fed72bc9089b31e2a5649a5538a2/src/appState/projectSignals.ts#L19

like

```typescript
export interface Project {
    id: string
    name: string

    // now the new stuff
    simulationStep: number,
    externalReference?: GeoJSON.Feature<GeoGJSON.Polygon, {externalId: string | number, type: 'Flurstueck' | 'user-created'}>
}
```

@JesJehle any comments or thoughts on this before I go into implementation?
Extending the model is easy, but I will have to change some of the core signals to respond to this change. So, I would like to do it only once. Anything you can think of, a project might additionally need? (description, owner, permission, thumbnail, external_url)

**Comment by JesJehle** [comment]
Would the slider go back immediately back to 1 after save or after restart?
I think the problem also is, that different tree lines don't save their age state separately.
Do we want this, or is it ok to have one age slider for all tree? So all trees have the same age.
In case of one age slider for all trees, since the slider is more like an animation feature, its fine to be reset to 1 after restart.
But if we want to have different tree line ages, saving it would make sense.
We should discuss this with Chris and for now only use 1 age for all trees.

**Comment by mmaelicke** [comment]
No, each Tree has its own age. As the User cannot change trees individually, all trees in one line end up with the same age. But age is a Tree property. 
The 'bug' is soley that the Simulation slider is net reseted. But i will fix that
