### ISSUE TITLE
Disable automatic layer switch

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#68]
When the user starts simulating with the slider, the layer for showing the canopy is auto selected. Thus the tree symbols disappear, which feels really unintuitive. We should disable this auto switch.

By that, we will loose the only 'spatial' result visualization, and the user has to magically stumble across the layer switch to find out about the canopy layer even existing.

Not sure how to tackle that other than with A/B testing. may do the auto switch only after 10 or 30 years of simulation? @JesJehle? 
I do not really have a favorite here, I dislike all options.

**Comment by mmaelicke** [comment]
we need a decision here, not much time left till the Milestone ends...

**Comment by JesJehle** [comment]
I would suggest to always show the tree icons
