### ISSUE TITLE
Questionmark vs Default tree

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#69]
With #65 we replaced the default tree icon.
I think using the Questionmark symbol for the tree type 'unbekannte Art' is a good idea. Questionmark seems to me a bad choice for cases where we simply don't have a specific icon. I would add the default-tree icon to any non-processed tree icon (and future tree types that do not yet have their own icon) and use the question **only** if we actually do not know. 
In any other cases, we actually know something (ie. being a Mehlbeere, we just lack a nice icon).

Also, on my screen the icon look really, really bad in terms of resolution. Should check that on different devices and screen resolutions.

**Comment by JesJehle** [comment]
Since, we use single trees and the user needs to select one first, this is not further relevant.
