### ISSUE TITLE
Navigate to tree details after successful editing of a new tree line

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#78]
As discussed. I think this is best implemented by you.
Pressing the button to accept editing should navigate to the respective tree details, with unbekannt baumart as default.

**Comment by mmaelicke** [comment]
yep, can do that. 
Always requiring the user to specify a Baumart is one extra click though. Maybe we just decide on the most common as default and try to get rid of a 'unbekannte art', as we can't visualize anything with that at all anyways. We kind of also make assumptions about the spacing, so why not the Baumart? What do you think?

**Comment by JesJehle** [comment]
True, we should talk to chris about this, but it would make things more simple.
@mmaelicke I think this would be great if implemented until the meeting
