### ISSUE TITLE
Session replay of canvas

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#80]
Regarding the canvas problem, I found this issue: https://github.com/PostHog/posthog/issues/14555
I found [higlight.io](https://www.highlight.io/), they seem to have solved the problem and also include error monitoring and logging: https://www.highlight.io/docs/getting-started/client-sdk/replay-configuration/canvas

Since for us, session replay of the canvas is probably the most important analysis we get and the integration seems to be [free](https://www.highlight.io/pricing) and [simple](https://www.highlight.io/docs/getting-started/client-sdk/reactjs). Why not also just drop it in? I am sorry it sucks, I know.

#79 #54

**Comment by mmaelicke** [comment]
Dies this use a Cookie again? :)

**Comment by JesJehle** [comment]
Yes, its seems like it. I would only use it during development only...

**Comment by mmaelicke** [comment]
I'll close this one, following the last few comments in #79 

If we need to change the posthog settings or go for another solution, we can re-open this issue. But for now I consider this one solved
