### ISSUE TITLE
If a new project is saved, all temporary work is lost

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#81]
I would say, we dont need to solve this until tomorrow.

- [ ] Problem 1 Button should only apprear if editing is true
- [ ] Problem 2 If a new project is saved, all temporary work is lost

https://www.loom.com/share/bae064efebc34e4ab5e6a821cdd9ccc0?sid=f894ae77-d9ae-4d95-a0b0-892b8238b464

**Comment by mmaelicke** [comment]
does not apply anymore
