### ISSUE TITLE
Real-sized tree images

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#86]
It was requested that we render real-sized images.

This is a bit more work as we need to figure out dynamically, **where** the tree should be, and calculate the bounding box of the raster from the tree height and the canopy width. This has then to be geferenced and added a source per tree to the map. Most tricky will be to keep track of when trees change their size / location, as we need to remove the old source, re-render the map and add the new, updated source.

**Comment by JesJehle** [comment]
No longer needed
