### ISSUE TITLE
Adding Landing Page

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#89]
Add a landing page which provides basic information about the tools, shows projects or the possibility to add a new one.
Basic idea:
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/0f9bbb73-47f3-4748-ac1a-1ba6fb3d74fd)

**Comment by mmaelicke** [comment]
@karpaddel @noobla11 

You want something else here right? So can this issue be closed?

**Comment by noobla11** [comment]
Yes can be closed
