### ISSUE TITLE
Adding starter page to input Initial site information

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#90]
Ideal Workflow:
1. Find my area
2. Draw reference area
3. Start adding tree to the map
4. Do everything else later on the summary page.

This information is needed before planing the system
- [x] Adding geocoding and search to find a location
- [ ] #129

This could also be requests on the summary page on the first visit #91 
- [ ] Input the Name of the agroforestry system
- [ ] Request information about the current site (Ackerland, Grünland, Dauerkultur)
- [ ] Request information about soil
- [ ] Request information about the land ownership
- [ ] Soll das Agroforstsystem im Gewässerrandstreifen angelegt werden?

Automated:
* Naturschutzgebiet, FFH, Natura2000, Biotop (automated)

**Comment by JesJehle** [comment]
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/7f5163df-e31b-4359-a1f6-81fc106ee630)
https://whimsical.com/integra-YWXzyTALywxcgLRzS2Q3u3

**Comment by mmaelicke** [comment]
I will close this issue, as we are not going down this path
