### ISSUE TITLE
update tree line Editor 

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#92]
Update of the tree line Editor:

- [ ] adding back the tree line list items of the previous version
- [ ] adding back the summary from the previous version
- [ ] selected tree lines are visible
- [ ] add option to delete tree lines
- [ ] add option to zoom to treelines (optional)

**Comment by JesJehle** [comment]
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/3f93cc89-efef-4b5e-9ceb-23080d4c4c74)
https://whimsical.com/integra-YWXzyTALywxcgLRzS2Q3u3

**Comment by mmaelicke** [comment]
done
