### ISSUE TITLE
Tree icon identification

### ISSUE THREAD

**Issue by noobla11** [hydrocode-de/integra-frontend#95]
Size: S, M, L, XL, age classes: 1-5, 6-20, 11-50, 51-100

'Season': flowering, summer, autumn and winter

Form : conicalslender, conicalwide, roundsmall, roundwide

In case we have enough individual pictures the tree species could also be added.

Example: s_winter_conicalslender_prunusavium.png

**Comment by mmaelicke** [comment]
This is clear and fully implemented, so I'll close here
